KT-26629 Inspection to replace `==` operator on Double.NaN with `equals` call
devbridie/kotlin pull request #6
Opened 2019-03-21 17:21 UTC by devbridie

YouTrack: https://youtrack.jetbrains.com/issue/KT-26629

Converts `5.0 == Double.NaN` to ` 5.0.equals(Double.NaN)`.

2019-03-22 12:30 UTC, jan-gerling approved these changes

2019-03-22 13:08 UTC, abansagi requested changes

2019-03-22 13:08 UTC, Austaon commented on idea/resources/inspectionDescriptions/ConvertEqualsDoubleNaN.html
> +This inspection reports <b>a == Double.NaN</b> should be <b>a.equals(Double.NaN)</b>.
This sentence is bad, and you should feel bad. 👿

2019-03-25 08:13 UTC, KilianCallebaut approved these changes

2019-03-25 10:55 UTC, abansagi approved these changes

2019-03-26 22:55 UTC, closed without merging