KT-12721 inspection should be made for converting Integer.toString(int) to int.toString()
devbridie/kotlin pull request #7
Opened 2019-03-25 10:16 UTC by Austaon

YouTrack: https://youtrack.jetbrains.com/issue/KT-12721
GitLab: https://gitlab.ewi.tudelft.nl/in4315/2018-2019/TI3125TU-swa-20-kotlin/swa-20-kotlin/issues/26

Please let @devbridie review this first, as I'm not 100% sure I implemented this correctly.

Example:

```
fun foo() {
    var number = 5
    val numberString = Integer.toString(number)
}
```

to

```
fun foo() {
    var number = 5
    val numberString = number.toString()
}

2019-03-25 10:28 UTC, devbridie requested changes
Nicely done!

2019-03-25 10:28 UTC, devbridie commented on idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceJavaToStringToIntToString.kt
> +        integerClass.replace(KtPsiFactory(integerClass).createExpression(integerArg.text))
I think you can use `integerClass.replace(integerArg))`?

2019-03-25 10:28 UTC, devbridie commented on idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceJavaToStringToIntToString.kt
> +    return fqName.equals("java.lang.Integer.toString")
`==` is more idomatic here

2019-03-25 10:28 UTC, devbridie commented on idea/resources/inspectionDescriptions/ReplaceJavaToStringToIntToString.html
> +This inspection reports explicit calls of <b>Integer.toString(int)</b> which can be replaced with <b>Int.toString()</b>
second `Int` should be `int` to match the first use

2019-03-25 10:28 UTC, devbridie commented on idea/resources/META-INF/plugin-common.xml
> +                     displayName="Replace 'Integer.toString(int)' to 'int.toString()'"
to -> with

2019-03-25 10:28 UTC, devbridie commented on idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceJavaToStringToIntToString.kt
> +class ReplaceJavaToStringToIntToString : AbstractKotlinInspection() {
* Needs `Inspection`
* `ReplaceJavaIntegerToStringWithMemberInspection`? :thinking:

2019-03-25 10:28 UTC, devbridie commented on idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceJavaToStringToIntToString.kt
> +
remove

2019-03-25 10:28 UTC, devbridie commented on idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceJavaToStringToIntToString.kt
> +class ConvertIntegerToStringQuickFix : LocalQuickFix {
this probably should be private

2019-03-25 10:28 UTC, devbridie commented on idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceJavaToStringToIntToString.kt
> +        integerClass.replace(KtPsiFactory(integerClass).createExpression(integerArg.text))
and otherwise you should reuse `KtPsiFactory(element)` in the second call.

2019-03-25 11:08 UTC, devbridie approved these changes

2019-03-27 12:40 UTC, KilianCallebaut approved these changes

2019-03-27 12:41 UTC, jan-gerling approved these changes
I don't think it is necessary, but you might test if other types e.g. Long stay the same.

2019-03-27 12:55 UTC, closed without merging